myproject/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name='base'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug_post>/', views.post_detail, name='post_detail'),
    path('tag/<slug:tag_slug>', views.post_list, name='post_list_by_tag'),
    #
    path('post/new/', views.PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/delete/', views.PostDelateView.as_view(), name='post_delete'),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.views import register, profile, logout_confirm
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('logout_confirm/', logout_confirm, name='logout_confirm'),

    path('', include(('blog.urls', 'blog'), namespace='blog')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from PIL import Image
class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    tags = TaggableManager()

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True)#unique_for_date='publish'
    author = models.ForeignKey(User, related_name='blog_posts', on_delete=models.CASCADE)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    #status = models.BooleanField(default=True)
    status = models.CharField(max_length=15, choices=STATUS_CHOICES, default='draft')

    class Meta:
        ordering = ('-publish', )
        verbose_name = 'Пост'
        verbose_name_plural = 'Пости' #у множині

    def __str__(self):
        return self.title


    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[
                           self.publish.year,
                           self.publish.strftime('%m'),
                           self.publish.strftime('%d'),
                           self.slug
                       ])


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)


    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE )
    image = models.ImageField(default='default.png', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} profile'


    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

myproject/blog/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Comment, Profile
from django.contrib.auth.forms import UserCreationForm

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

myproject/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import CommentForm, UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib import messages #меседжі користувачу
from taggit.models import Tag
from django.shortcuts import redirect#перенаправлення
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

def post_list(request, tag_slug=None):
    posts = Post.objects.filter(status='published')
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = posts.filter(tags__in=[tag])



    paginator = Paginator(posts, 3)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)



    return render(request, 'blog/post/list.html',{'posts': posts, 'page': page,
                                                                         'tag': tag})


def post_detail(request, year, month, day, slug_post):
    post = get_object_or_404(Post, status='published',
                                   slug=slug_post,
                                   publish__year = year,
                                   publish__month = month ,
                                   publish__day = day)

    comments = post.comments.filter(active=True)

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()


    context = {'post': post,
               'comments': comments,
                'comment_form': comment_form}
    return render(request, 'blog/post/detail.html', context=context)



def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Створено акаунт {username}!')
            return redirect('login')
    else:
        form = UserRegisterForm()

    return render(request, 'users/register.html', {'form': form})

@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user) ##instance=request.user візьмуться поточні дані з профілю
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            return redirect('profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request, 'users/profile.html', context=context)

def logout_confirm(request):
    return render(request, 'users/logout_confirm.html')


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'body', 'slug']

    def form_valid(self, form):
        form.instance.author = self.request.user #поєднує автора з новим постом
        return super().form_valid(form) # зветраємось у батьківський клас

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'body', 'slug']

    def form_valid(self, form):
        form.instance.author = self.request.user  # поєднує автора з новим постом
        return super().form_valid(form)  # зветраємось у батьківський клас

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

class PostDelateView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    #перевіряємо чи є він автором
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

myproject/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}

<!--{#% load blog_tags %}-->
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>My blog</title>
        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
        <link href="{% static 'css/blog.css' %}" rel="stylesheet" type="text/css"/> <!--{% static 'css/blog.css' %}-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    </head>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3" href="/">My blog</a>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            <!-- Navbar-->

            {% if user.is_authenticated %}
            	<a class="navbar-brand ps-3" href="{% url 'profile' %}">Профіль</a>
            	<a class="navbar-brand ps-3" href="{% url 'logout_confirm' %}">Вихід</a>
                <a class="navbar-brand ps-3" href="{% url 'blog:post_create' %}">Новий пост</a>
          	{% else %}
            	<a class="navbar-brand ps-3" href="{% url 'login' %}">Вхід</a>
            	<a class="navbar-brand ps-3" href="{% url 'register' %}">Реєстрація</a>
          	{% endif %}

            <a class="navbar-brand ps-3" href="{#% url 'blog:blog_about' %}">Про блог</a>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <a class="nav-link" href="index.html">
                                My blog
                            </a>
                            <!--
                            <a class="nav-link collapsed" href="{#% url 'blog:post_feed' %}">Subscribe to my RSS feed</a>

                            <div class="sb-sidenav-collapse-arrow">
                                <h3 class="card-header">Latest posts</h3>
                                {#% show_latest_posts 3 %}
                            </div>
                            <div class="sb-sidenav-collapse-arrow">
                                <p class="card-header">This is my blog. I've written {#% total_posts %} posts so far.</p>
                            </div>
                            -->
                        </div>
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid px-4">
                        <h1 class="mt-4">My blog</h1>
                        <div class="row">
                            <!--
                            {#% if messages %}
                                {#% for message in messages %}
                                    <div class="alert alert-{#{ message.tags }}">
                                        {#{ message }}
                                    </div>
                                {#% endfor %}
                            {#% endif %}
                            -->
                            {% block content %}
                            {% endblock %}
                        </div>
                    </div>
                </main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2024</div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
    </body>
</html>

myproject/blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Видалення запису</legend>
                <h2>Ви впевнені, що хочете видалити цей запис?"{{ post.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Так, хочу видалити</button>
                <a class="btn btn-outline-secondary" href="{{ post.get_absolute_url }}">Відміна</a>
            </div>
        </form>
    </div>
{% endblock content %}

myproject/blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Новий запис</legend>
                {{ form.as_p }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Зберегти</button>
            </div>
        </form>
    </div>
{% endblock content %}