myproject/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name='base'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug_post>/', views.post_detail, name='post_detail'),
    path('tag/<slug:tag_slug>', views.post_list, name='post_list_by_tag'),
    #
    path('post/new/', views.PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/delete/', views.PostDelateView.as_view(), name='post_delete'),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.views import register, profile, logout_confirm
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('logout_confirm/', logout_confirm, name='logout_confirm'),

    path('', include(('blog.urls', 'blog'), namespace='blog')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from PIL import Image
class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    tags = TaggableManager()

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True)#unique_for_date='publish'
    author = models.ForeignKey(User, related_name='blog_posts', on_delete=models.CASCADE)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    #status = models.BooleanField(default=True)
    status = models.CharField(max_length=15, choices=STATUS_CHOICES, default='draft')

    class Meta:
        ordering = ('-publish', )
        verbose_name = 'Пост'
        verbose_name_plural = 'Пости' #у множині

    def __str__(self):
        return self.title


    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[
                           self.publish.year,
                           self.publish.strftime('%m'),
                           self.publish.strftime('%d'),
                           self.slug
                       ])


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)


    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE )
    image = models.ImageField(default='default.png', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} profile'


    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

myproject/blog/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Comment, Profile
from django.contrib.auth.forms import UserCreationForm

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

myproject/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import CommentForm, UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib import messages #меседжі користувачу
from taggit.models import Tag
from django.shortcuts import redirect#перенаправлення
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

def post_list(request, tag_slug=None):
    posts = Post.objects.filter(status='published')
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = posts.filter(tags__in=[tag])



    paginator = Paginator(posts, 3)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)



    return render(request, 'blog/post/list.html',{'posts': posts, 'page': page,
                                                                         'tag': tag})


def post_detail(request, year, month, day, slug_post):
    post = get_object_or_404(Post, status='published',
                                   slug=slug_post,
                                   publish__year = year,
                                   publish__month = month ,
                                   publish__day = day)

    comments = post.comments.filter(active=True)

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()


    context = {'post': post,
               'comments': comments,
                'comment_form': comment_form}
    return render(request, 'blog/post/detail.html', context=context)



def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Створено акаунт {username}!')
            return redirect('login')
    else:
        form = UserRegisterForm()

    return render(request, 'users/register.html', {'form': form})

@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user) ##instance=request.user візьмуться поточні дані з профілю
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            return redirect('profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request, 'users/profile.html', context=context)

def logout_confirm(request):
    return render(request, 'users/logout_confirm.html')


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'body', 'slug']

    def form_valid(self, form):
        form.instance.author = self.request.user #поєднує автора з новим постом
        return super().form_valid(form) # зветраємось у батьківський клас

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'body', 'slug']

    def form_valid(self, form):
        form.instance.author = self.request.user  # поєднує автора з новим постом
        return super().form_valid(form)  # зветраємось у батьківський клас

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

class PostDelateView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    #перевіряємо чи є він автором
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

myproject/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
<!--{#% load blog_tags %}-->
{% load crispy_forms_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}

    <h1 class="card-header">{{ post.title }}</h1>
    <p class="text-muted fst-italic mb-2">
        Published {{ post.publish }} by {{ post.author }}
    </p>
        <p class="data_post"> {{ post.body }} </p>
        <!--
    <p>
        <a href="{#% url 'blog:post_share' post.id %}">Поділитися</a>
    </p>
    -->
    <p>
        <a href="{% url 'blog:post_update' post.id %}">Оновити</a>
    </p>
    <p>
        <a href="{% url 'blog:post_delete' post.id %}">Видалити</a>
    </p>
 <!--
<h2>Similar posts</h2>
{#% for post in similar_posts %}
    <p>
        <a href="{#{ post.get_absolute_url }}">{#{ post.title }}</a>
    </p>
{#% empty %}
    There are no similar posts yet.
{#% endfor %}
-->
{% with comments.count as total_comments %}
    <h2>
        {{ total_comments }} comment {{ total_comments|pluralize }}
    </h2>
{% endwith %}
{% for comment in comments %}

        <div class="fw-bold">
            Comment {{ forloop.counter }} by {{ comment.name }}
        </div>
        <div class="text-muted fst-italic mb-2">
            {{ comment.created }}
        </div>
        <div class="fw-bold">
            {{ comment.body|linebreaks }}
        </div>

{% empty %}
    <p>There are no comments yet.</p>
{% endfor %}
{% if new_comment %}
    <h2>Your comment has been added.</h2>
{% else %}
    <h2>Add a new comment</h2>
    <form action="." method="post" class="mb-4">
        {% crispy comment_form %}
       <!-- {#{ comment_form.as_p }} -->
        {% csrf_token %}
        <p><input type="submit" value="Add comment"></p>
    </form>
{% endif %}

{% endblock %}

myproject/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block title %}My Blog{% endblock %}
{% block content %}
<!--
    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
-->
    {% for post in posts %}
        <h4>
            <a class="card-header" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h4>

            <p class="tags">Tags:
                {% for tag in post.tags.all %}
                    <a class="badge bg-secondary text-decoration-none link-light" href="{#% url 'blog:post_list_by_tag' tag.slug %}">
                        {{ tag.name }}
                    </a>
                    {% if not forloop.last %}, {% endif %}
                {% endfor %}
            </p>
        -->
        <p class="text-muted fst-italic mb-2">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|truncatewords:30|linebreaks }}
    {% endfor %}

    {% include "pagination.html" with page=posts %}

{% endblock %}